Import Libaries

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import (
    GradientBoostingClassifier
)
import xgboost as xgb
import matplotlib.pyplot as plt
import collections
import warnings

Read Dataset

In [ ]:
df = pd.read_csv('card_transdata.csv')
df = df.rename(columns={'fraud': 'target'})
df = df.dropna()
df = df.sample(n=1000)

Run Anova Test

In [ ]:
print('ANOVA Test')
from sklearn.feature_selection import SelectKBest, f_classif, chi2
x = df.loc[:, ['distance_from_home','distance_from_last_transaction','ratio_to_median_purchase_price']]
y = df.loc[:, 'target']

fs = SelectKBest(score_func=f_classif, k='all')  # call the method
bestFeatures = fs.fit(x, y)    # train the model
np.set_printoptions(suppress = True)
print(bestFeatures.scores_)    # print out the scores
print(bestFeatures.pvalues_)

ANOVA Test
[ 27.15374161  22.7440799  178.10008035]
[0.00000023 0.00000213 0.        ]


Run CHi-squared Test

In [ ]:
print('Chi-Squared')
x = df.loc[:, ['used_chip', 'repeat_retailer','used_pin_number','online_order']]
y = df.loc[:, 'target']

chi = SelectKBest(score_func=chi2, k='all')
catFeatures = chi.fit(x, y)
print(catFeatures.scores_)
print(catFeatures.pvalues_)

Chi-Squared
[ 2.91142573  0.27313608 10.43612335 11.18469488]
[0.08795409 0.60123578 0.00123574 0.00082475]


Train-Test split data set

In [ ]:
X = df[['used_pin_number','online_order','distance_from_home','distance_from_last_transaction','ratio_to_median_purchase_price']]
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

UnderSampling

In [ ]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=42, sampling_strategy = 'majority')
X_resampled, y_resampled = rus.fit_resample(X_train, y_train)

Gradient Boosting Classifer

In [ ]:
gb_clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=42)
gb_clf.fit(X_resampled.values, y_resampled.values)
y_pred_gb = gb_clf.predict(X_test.values)
accuracy_gb = accuracy_score(y_test, y_pred_gb)
print(f"Gradient Boosting Accuracy: {accuracy_gb * 100:.2f}%")

Gradient Boosting Accuracy: 94.00%


Logistic Regression

In [ ]:
#Prediction Model
print('prediction model')
from sklearn.linear_model import LogisticRegression
df = pd.DataFrame(data=df)
LogRegression = LogisticRegression( max_iter=2000)
LogRegression.fit(X_resampled, y_resampled)

from sklearn.metrics import accuracy_score
test_pred = LogRegression.predict(X_test)
accuracy_score(y_test, test_pred)

prediction model


0.8933333333333333

Pickle File

In [ ]:
from google.colab import drive
import pickle
path = '/content/drive/My Drive/model.pkl'
file = open(path, "wb")
pickle.dump(gb_clf, file)
file.close()


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
